# Generated by Django 4.2.7 on 2026-09-21 01:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='McpCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(db_comment='工具名称', max_length=100, verbose_name='工具名称')),
                ('args_digest', models.CharField(blank=True, db_comment='参数哈希摘要(不存原始参数)', default='', max_length=64, verbose_name='参数摘要')),
                ('args_brief', models.TextField(blank=True, db_comment='脱敏截断后的参数JSON(供审计回溯)', default='', verbose_name='参数详情')),
                ('client_name', models.CharField(blank=True, db_comment='发起调用的客户端标识(User-Agent)', default='', max_length=100, verbose_name='客户端')),
                ('status', models.CharField(choices=[('success', '成功'), ('error', '失败'), ('denied', '拒绝')], db_comment='调用结果', default='success', max_length=20, verbose_name='调用结果')),
                ('duration_ms', models.IntegerField(db_comment='耗时(毫秒)', default=0, verbose_name='耗时(毫秒)')),
                ('error', models.TextField(blank=True, db_comment='错误信息(截断)', default='', verbose_name='错误信息')),
                ('created_at', models.DateTimeField(db_comment='调用时间', default=django.utils.timezone.now, verbose_name='调用时间')),
            ],
            options={
                'verbose_name': 'MCP调用日志',
                'verbose_name_plural': 'MCP调用日志',
                'db_table': 'mcp_call_logs',
                'db_table_comment': 'MCP工具调用日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='McpPendingConfirm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(db_comment='待确认的工具名称', max_length=100, verbose_name='工具名称')),
                ('arguments', models.JSONField(blank=True, db_comment='工具参数(JSON)', default=dict, verbose_name='工具参数')),
                ('preview', models.TextField(blank=True, db_comment='影响描述文本', default='', verbose_name='影响预览')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('approved', '已批准'), ('rejected', '已拒绝'), ('consumed', '已消费'), ('expired', '已过期')], db_comment='状态', default='pending', max_length=20, verbose_name='状态')),
                ('awaiting_human', models.BooleanField(db_comment='人工审批模式下 confirm 已转待批', default=False, verbose_name='等待人工审批')),
                ('result', models.JSONField(blank=True, db_comment='批准/确认后执行结果摘要', default=dict, verbose_name='执行结果')),
                ('expires_at', models.DateTimeField(db_comment='confirm令牌过期时间(+5分钟)', verbose_name='过期时间')),
                ('created_at', models.DateTimeField(db_comment='创建时间', default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='更新时间', verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'MCP待确认操作',
                'verbose_name_plural': 'MCP待确认操作',
                'db_table': 'mcp_pending_confirms',
                'db_table_comment': 'MCP危险操作待确认',
                'ordering': ['-created_at'],
            },
        ),
    ]
