# Generated by Django 4.2.7 on 2026-09-21 01:27

import apps.monitor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('CRITICAL', '严重'), ('WARNING', '警告')], db_comment='级别', default='CRITICAL', max_length=20, verbose_name='级别')),
                ('message', models.TextField(db_comment='告警内容', verbose_name='告警内容')),
                ('status', models.CharField(choices=[('FIRING', '告警中'), ('ACKED', '已认领'), ('RESOLVED', '已恢复')], db_comment='状态', default='FIRING', max_length=20, verbose_name='状态')),
                ('first_triggered_at', models.DateTimeField(auto_now_add=True, db_comment='首次触发', verbose_name='首次触发')),
                ('last_triggered_at', models.DateTimeField(blank=True, db_comment='最近触发', null=True, verbose_name='最近触发')),
                ('resolved_at', models.DateTimeField(blank=True, db_comment='恢复时间', null=True, verbose_name='恢复时间')),
                ('acknowledged_at', models.DateTimeField(blank=True, db_comment='认领时间', null=True, verbose_name='认领时间')),
                ('send_detail', models.JSONField(db_comment='发送结果', default=list, verbose_name='发送结果')),
                ('notify_count', models.IntegerField(db_comment='已通知次数', default=0, verbose_name='已通知次数')),
                ('last_notified_at', models.DateTimeField(blank=True, db_comment='最近通知时间', null=True, verbose_name='最近通知时间')),
            ],
            options={
                'verbose_name': '告警记录',
                'verbose_name_plural': '告警记录',
                'db_table': 'monitor_alerts',
                'db_table_comment': '告警记录',
                'ordering': ['-last_triggered_at', '-first_triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='MonitorCheckLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('UP', '正常'), ('DOWN', '异常'), ('UNKNOWN', '未知')], db_comment='结果', default='UNKNOWN', max_length=10, verbose_name='结果')),
                ('latency_ms', models.IntegerField(blank=True, db_comment='延迟(ms)', null=True, verbose_name='延迟(ms)')),
                ('http_status', models.IntegerField(blank=True, db_comment='HTTP状态码', null=True, verbose_name='HTTP状态码')),
                ('error_message', models.TextField(blank=True, db_comment='错误信息', verbose_name='错误信息')),
                ('detail', models.JSONField(db_comment='响应摘要', default=dict, verbose_name='响应摘要')),
                ('triggered_alert', models.BooleanField(db_comment='是否触发告警', default=False, verbose_name='是否触发告警')),
                ('checked_at', models.DateTimeField(auto_now_add=True, db_comment='检测时间', verbose_name='检测时间')),
            ],
            options={
                'verbose_name': '探测记录',
                'verbose_name_plural': '探测记录',
                'db_table': 'monitor_check_logs',
                'db_table_comment': '探测记录',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='MonitorTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_comment='目标名称', max_length=200, unique=True, verbose_name='目标名称')),
                ('type', models.CharField(choices=[('LOGIN', '登录可用性'), ('HTTP', '接口存活'), ('ONLINE', '在线率'), ('DOCKER', '容器状态'), ('SL651', '遥测链路')], db_comment='探测类型', max_length=20, verbose_name='探测类型')),
                ('url', models.CharField(blank=True, db_comment='URL', max_length=500, verbose_name='URL')),
                ('method', models.CharField(db_comment='请求方法', default='GET', max_length=10, verbose_name='请求方法')),
                ('host', models.CharField(blank=True, db_comment='主机', max_length=200, verbose_name='主机')),
                ('port', models.IntegerField(blank=True, db_comment='端口', null=True, verbose_name='端口')),
                ('check_config', models.JSONField(db_comment='探测配置', default=dict, verbose_name='探测配置')),
                ('interval_seconds', models.IntegerField(db_comment='轮询间隔(秒)', default=60, verbose_name='轮询间隔(秒)')),
                ('alert_threshold', models.IntegerField(db_comment='告警阈值(连续失败次数)', default=3, verbose_name='告警阈值(连续失败次数)')),
                ('alert_repeat_interval', models.IntegerField(db_comment='自动重提醒间隔(分钟)', default=apps.monitor.models._default_alert_repeat_interval, verbose_name='自动重提醒间隔(分钟)')),
                ('manual_alert_cooldown', models.IntegerField(db_comment='手动检测告警冷却(分钟)', default=apps.monitor.models._default_manual_alert_cooldown, verbose_name='手动检测告警冷却(分钟)')),
                ('enabled', models.BooleanField(db_comment='启用', default=True, verbose_name='启用')),
                ('status', models.CharField(choices=[('UP', '正常'), ('DOWN', '异常'), ('UNKNOWN', '未知')], db_comment='当前状态', default='UNKNOWN', max_length=10, verbose_name='当前状态')),
                ('last_check_at', models.DateTimeField(blank=True, db_comment='最近检测时间', null=True, verbose_name='最近检测时间')),
                ('consecutive_failures', models.IntegerField(db_comment='连续失败次数', default=0, verbose_name='连续失败次数')),
                ('next_check_at', models.DateTimeField(blank=True, db_comment='下次检测时间', null=True, verbose_name='下次检测时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='更新时间', verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '监控目标',
                'verbose_name_plural': '监控目标',
                'db_table': 'monitor_targets',
                'db_table_comment': '监控目标',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_comment='渠道名称', max_length=100, unique=True, verbose_name='渠道名称')),
                ('type', models.CharField(choices=[('DINGTALK', '钉钉'), ('WECOM', '企业微信'), ('EMAIL', '邮件')], db_comment='渠道类型', max_length=20, verbose_name='渠道类型')),
                ('config', models.JSONField(db_comment='渠道配置', default=dict, verbose_name='渠道配置')),
                ('enabled', models.BooleanField(db_comment='启用', default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='更新时间', verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '通知渠道',
                'verbose_name_plural': '通知渠道',
                'db_table': 'monitor_channels',
                'db_table_comment': '通知渠道',
                'ordering': ['-created_at'],
            },
        ),
    ]
